/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"
void   event__init
                     (Event         *message)
{
  static const Event init_value = EVENT__INIT;
  *message = init_value;
}
size_t event__get_packed_size
                     (const Event *message)
{
  assert(message->base.descriptor == &event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t event__pack
                     (const Event *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t event__pack_to_buffer
                     (const Event *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Event *
       event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Event *)
     protobuf_c_message_unpack (&event__descriptor,
                                allocator, len, data);
}
void   event__free_unpacked
                     (Event *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   command__init
                     (Command         *message)
{
  static const Command init_value = COMMAND__INIT;
  *message = init_value;
}
size_t command__get_packed_size
                     (const Command *message)
{
  assert(message->base.descriptor == &command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t command__pack
                     (const Command *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t command__pack_to_buffer
                     (const Command *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Command *
       command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Command *)
     protobuf_c_message_unpack (&command__descriptor,
                                allocator, len, data);
}
void   command__free_unpacked
                     (Command *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   car_sensor__init
                     (CarSensor         *message)
{
  static const CarSensor init_value = CAR_SENSOR__INIT;
  *message = init_value;
}
size_t car_sensor__get_packed_size
                     (const CarSensor *message)
{
  assert(message->base.descriptor == &car_sensor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t car_sensor__pack
                     (const CarSensor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &car_sensor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t car_sensor__pack_to_buffer
                     (const CarSensor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &car_sensor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CarSensor *
       car_sensor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CarSensor *)
     protobuf_c_message_unpack (&car_sensor__descriptor,
                                allocator, len, data);
}
void   car_sensor__free_unpacked
                     (CarSensor *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &car_sensor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stint_data__init
                     (StintData         *message)
{
  static const StintData init_value = STINT_DATA__INIT;
  *message = init_value;
}
size_t stint_data__get_packed_size
                     (const StintData *message)
{
  assert(message->base.descriptor == &stint_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stint_data__pack
                     (const StintData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stint_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stint_data__pack_to_buffer
                     (const StintData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stint_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StintData *
       stint_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StintData *)
     protobuf_c_message_unpack (&stint_data__descriptor,
                                allocator, len, data);
}
void   stint_data__free_unpacked
                     (StintData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stint_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lap__init
                     (Lap         *message)
{
  static const Lap init_value = LAP__INIT;
  *message = init_value;
}
size_t lap__get_packed_size
                     (const Lap *message)
{
  assert(message->base.descriptor == &lap__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lap__pack
                     (const Lap *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lap__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lap__pack_to_buffer
                     (const Lap *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lap__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Lap *
       lap__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Lap *)
     protobuf_c_message_unpack (&lap__descriptor,
                                allocator, len, data);
}
void   lap__free_unpacked
                     (Lap *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lap__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lap_data__init
                     (LapData         *message)
{
  static const LapData init_value = LAP_DATA__INIT;
  *message = init_value;
}
size_t lap_data__get_packed_size
                     (const LapData *message)
{
  assert(message->base.descriptor == &lap_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lap_data__pack
                     (const LapData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lap_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lap_data__pack_to_buffer
                     (const LapData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lap_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LapData *
       lap_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LapData *)
     protobuf_c_message_unpack (&lap_data__descriptor,
                                allocator, len, data);
}
void   lap_data__free_unpacked
                     (LapData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lap_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mcu_data__init
                     (McuData         *message)
{
  static const McuData init_value = MCU_DATA__INIT;
  *message = init_value;
}
size_t mcu_data__get_packed_size
                     (const McuData *message)
{
  assert(message->base.descriptor == &mcu_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mcu_data__pack
                     (const McuData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mcu_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mcu_data__pack_to_buffer
                     (const McuData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mcu_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
McuData *
       mcu_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (McuData *)
     protobuf_c_message_unpack (&mcu_data__descriptor,
                                allocator, len, data);
}
void   mcu_data__free_unpacked
                     (McuData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mcu_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor event__field_descriptors[6] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Event, has_id),
    offsetof(Event, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Event, has_type),
    offsetof(Event, type),
    &event_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "severity",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Event, has_severity),
    offsetof(Event, severity),
    &severity__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "created_at",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Event, has_created_at),
    offsetof(Event, created_at),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "displayed_since",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Event, has_displayed_since),
    offsetof(Event, displayed_since),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "text",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Event, text),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned event__field_indices_by_name[] = {
  3,   /* field[3] = created_at */
  4,   /* field[4] = displayed_since */
  0,   /* field[0] = id */
  2,   /* field[2] = severity */
  5,   /* field[5] = text */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "event",
  "Event",
  "Event",
  "",
  sizeof(Event),
  6,
  event__field_descriptors,
  event__field_indices_by_name,
  1,  event__number_ranges,
  (ProtobufCMessageInit) event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor command__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Command, has_type),
    offsetof(Command, type),
    &command_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "created",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Command, has_created),
    offsetof(Command, created),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "handled",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Command, has_handled),
    offsetof(Command, handled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned command__field_indices_by_name[] = {
  1,   /* field[1] = created */
  2,   /* field[2] = handled */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "command",
  "Command",
  "Command",
  "",
  sizeof(Command),
  3,
  command__field_descriptors,
  command__field_indices_by_name,
  1,  command__number_ranges,
  (ProtobufCMessageInit) command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor car_sensor__field_descriptors[2] =
{
  {
    "temp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CarSensor, has_temp),
    offsetof(CarSensor, temp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "preassure",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(CarSensor, has_preassure),
    offsetof(CarSensor, preassure),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned car_sensor__field_indices_by_name[] = {
  1,   /* field[1] = preassure */
  0,   /* field[0] = temp */
};
static const ProtobufCIntRange car_sensor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor car_sensor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "car_sensor",
  "CarSensor",
  "CarSensor",
  "",
  sizeof(CarSensor),
  2,
  car_sensor__field_descriptors,
  car_sensor__field_indices_by_name,
  1,  car_sensor__number_ranges,
  (ProtobufCMessageInit) car_sensor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stint_data__field_descriptors[4] =
{
  {
    "running",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(StintData, has_running),
    offsetof(StintData, running),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enabled",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(StintData, has_enabled),
    offsetof(StintData, enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(StintData, has_target),
    offsetof(StintData, target),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "elapsed",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(StintData, has_elapsed),
    offsetof(StintData, elapsed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stint_data__field_indices_by_name[] = {
  3,   /* field[3] = elapsed */
  1,   /* field[1] = enabled */
  0,   /* field[0] = running */
  2,   /* field[2] = target */
};
static const ProtobufCIntRange stint_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor stint_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "stint_data",
  "StintData",
  "StintData",
  "",
  sizeof(StintData),
  4,
  stint_data__field_descriptors,
  stint_data__field_indices_by_name,
  1,  stint_data__number_ranges,
  (ProtobufCMessageInit) stint_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lap__field_descriptors[2] =
{
  {
    "lap_no",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Lap, has_lap_no),
    offsetof(Lap, lap_no),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lap_time_ms",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Lap, has_lap_time_ms),
    offsetof(Lap, lap_time_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lap__field_indices_by_name[] = {
  0,   /* field[0] = lap_no */
  1,   /* field[1] = lap_time_ms */
};
static const ProtobufCIntRange lap__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor lap__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lap",
  "Lap",
  "Lap",
  "",
  sizeof(Lap),
  2,
  lap__field_descriptors,
  lap__field_indices_by_name,
  1,  lap__number_ranges,
  (ProtobufCMessageInit) lap__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lap_data__field_descriptors[4] =
{
  {
    "lap_no",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(LapData, has_lap_no),
    offsetof(LapData, lap_no),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "best_lap",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(LapData, has_best_lap),
    offsetof(LapData, best_lap),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_lap",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(LapData, has_current_lap),
    offsetof(LapData, current_lap),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "laps",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LapData, n_laps),
    offsetof(LapData, laps),
    &lap__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lap_data__field_indices_by_name[] = {
  1,   /* field[1] = best_lap */
  2,   /* field[2] = current_lap */
  0,   /* field[0] = lap_no */
  3,   /* field[3] = laps */
};
static const ProtobufCIntRange lap_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor lap_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lap_data",
  "LapData",
  "LapData",
  "",
  sizeof(LapData),
  4,
  lap_data__field_descriptors,
  lap_data__field_indices_by_name,
  1,  lap_data__number_ranges,
  (ProtobufCMessageInit) lap_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mcu_data__field_descriptors[11] =
{
  {
    "network_time_adjustment",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(McuData, has_network_time_adjustment),
    offsetof(McuData, network_time_adjustment),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "water",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(McuData, water),
    &car_sensor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "oil",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(McuData, oil),
    &car_sensor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gas",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(McuData, gas),
    &car_sensor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stint",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(McuData, stint),
    &stint_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lap_data",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(McuData, lap_data),
    &lap_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "events",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(McuData, n_events),
    offsetof(McuData, events),
    &event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outgoing_commands",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(McuData, n_outgoing_commands),
    offsetof(McuData, outgoing_commands),
    &command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outgoing_commands_last_idx",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(McuData, has_outgoing_commands_last_idx),
    offsetof(McuData, outgoing_commands_last_idx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "incoming_commands",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(McuData, n_incoming_commands),
    offsetof(McuData, incoming_commands),
    &command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "incoming_commands_last_idx",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(McuData, has_incoming_commands_last_idx),
    offsetof(McuData, incoming_commands_last_idx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mcu_data__field_indices_by_name[] = {
  6,   /* field[6] = events */
  3,   /* field[3] = gas */
  9,   /* field[9] = incoming_commands */
  10,   /* field[10] = incoming_commands_last_idx */
  5,   /* field[5] = lap_data */
  0,   /* field[0] = network_time_adjustment */
  2,   /* field[2] = oil */
  7,   /* field[7] = outgoing_commands */
  8,   /* field[8] = outgoing_commands_last_idx */
  4,   /* field[4] = stint */
  1,   /* field[1] = water */
};
static const ProtobufCIntRange mcu_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor mcu_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mcu_data",
  "McuData",
  "McuData",
  "",
  sizeof(McuData),
  11,
  mcu_data__field_descriptors,
  mcu_data__field_indices_by_name,
  1,  mcu_data__number_ranges,
  (ProtobufCMessageInit) mcu_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue severity__enum_values_by_number[4] =
{
  { "POSITIVE", "SEVERITY__POSITIVE", 1 },
  { "NORMAL", "SEVERITY__NORMAL", 2 },
  { "WARN", "SEVERITY__WARN", 3 },
  { "CRIT", "SEVERITY__CRIT", 4 },
};
static const ProtobufCIntRange severity__value_ranges[] = {
{1, 0},{0, 4}
};
static const ProtobufCEnumValueIndex severity__enum_values_by_name[4] =
{
  { "CRIT", 3 },
  { "NORMAL", 1 },
  { "POSITIVE", 0 },
  { "WARN", 2 },
};
const ProtobufCEnumDescriptor severity__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "severity",
  "severity",
  "Severity",
  "",
  4,
  severity__enum_values_by_number,
  4,
  severity__enum_values_by_name,
  1,
  severity__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue event_type__enum_values_by_number[4] =
{
  { "EVT_NONE", "EVENT_TYPE__EVT_NONE", 1 },
  { "EVT_LAP", "EVENT_TYPE__EVT_LAP", 2 },
  { "EVT_TIME_REMAIN", "EVENT_TYPE__EVT_TIME_REMAIN", 3 },
  { "EVT_STATE_CHANGE", "EVENT_TYPE__EVT_STATE_CHANGE", 4 },
};
static const ProtobufCIntRange event_type__value_ranges[] = {
{1, 0},{0, 4}
};
static const ProtobufCEnumValueIndex event_type__enum_values_by_name[4] =
{
  { "EVT_LAP", 1 },
  { "EVT_NONE", 0 },
  { "EVT_STATE_CHANGE", 3 },
  { "EVT_TIME_REMAIN", 2 },
};
const ProtobufCEnumDescriptor event_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "event_type",
  "event_type",
  "EventType",
  "",
  4,
  event_type__enum_values_by_number,
  4,
  event_type__enum_values_by_name,
  1,
  event_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue command_type__enum_values_by_number[4] =
{
  { "COM_NONE", "COMMAND_TYPE__COM_NONE", 1 },
  { "COM_PIT", "COMMAND_TYPE__COM_PIT", 2 },
  { "COM_STINT_OVER", "COMMAND_TYPE__COM_STINT_OVER", 3 },
  { "COM_TBD", "COMMAND_TYPE__COM_TBD", 4 },
};
static const ProtobufCIntRange command_type__value_ranges[] = {
{1, 0},{0, 4}
};
static const ProtobufCEnumValueIndex command_type__enum_values_by_name[4] =
{
  { "COM_NONE", 0 },
  { "COM_PIT", 1 },
  { "COM_STINT_OVER", 2 },
  { "COM_TBD", 3 },
};
const ProtobufCEnumDescriptor command_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "command_type",
  "command_type",
  "CommandType",
  "",
  4,
  command_type__enum_values_by_number,
  4,
  command_type__enum_values_by_name,
  1,
  command_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
