/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"
void   proto__event__init
                     (ProtoEvent         *message)
{
  static const ProtoEvent init_value = PROTO__EVENT__INIT;
  *message = init_value;
}
size_t proto__event__get_packed_size
                     (const ProtoEvent *message)
{
  assert(message->base.descriptor == &proto__event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__event__pack
                     (const ProtoEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__event__pack_to_buffer
                     (const ProtoEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoEvent *
       proto__event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoEvent *)
     protobuf_c_message_unpack (&proto__event__descriptor,
                                allocator, len, data);
}
void   proto__event__free_unpacked
                     (ProtoEvent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__command__init
                     (ProtoCommand         *message)
{
  static const ProtoCommand init_value = PROTO__COMMAND__INIT;
  *message = init_value;
}
size_t proto__command__get_packed_size
                     (const ProtoCommand *message)
{
  assert(message->base.descriptor == &proto__command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__command__pack
                     (const ProtoCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__command__pack_to_buffer
                     (const ProtoCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoCommand *
       proto__command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoCommand *)
     protobuf_c_message_unpack (&proto__command__descriptor,
                                allocator, len, data);
}
void   proto__command__free_unpacked
                     (ProtoCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__car__sensor__init
                     (ProtoCarSensor         *message)
{
  static const ProtoCarSensor init_value = PROTO__CAR__SENSOR__INIT;
  *message = init_value;
}
size_t proto__car__sensor__get_packed_size
                     (const ProtoCarSensor *message)
{
  assert(message->base.descriptor == &proto__car__sensor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__car__sensor__pack
                     (const ProtoCarSensor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__car__sensor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__car__sensor__pack_to_buffer
                     (const ProtoCarSensor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__car__sensor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoCarSensor *
       proto__car__sensor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoCarSensor *)
     protobuf_c_message_unpack (&proto__car__sensor__descriptor,
                                allocator, len, data);
}
void   proto__car__sensor__free_unpacked
                     (ProtoCarSensor *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__car__sensor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__stint__data__init
                     (ProtoStintData         *message)
{
  static const ProtoStintData init_value = PROTO__STINT__DATA__INIT;
  *message = init_value;
}
size_t proto__stint__data__get_packed_size
                     (const ProtoStintData *message)
{
  assert(message->base.descriptor == &proto__stint__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__stint__data__pack
                     (const ProtoStintData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__stint__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__stint__data__pack_to_buffer
                     (const ProtoStintData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__stint__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoStintData *
       proto__stint__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoStintData *)
     protobuf_c_message_unpack (&proto__stint__data__descriptor,
                                allocator, len, data);
}
void   proto__stint__data__free_unpacked
                     (ProtoStintData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__stint__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__lap__init
                     (ProtoLap         *message)
{
  static const ProtoLap init_value = PROTO__LAP__INIT;
  *message = init_value;
}
size_t proto__lap__get_packed_size
                     (const ProtoLap *message)
{
  assert(message->base.descriptor == &proto__lap__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__lap__pack
                     (const ProtoLap *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__lap__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__lap__pack_to_buffer
                     (const ProtoLap *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__lap__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoLap *
       proto__lap__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoLap *)
     protobuf_c_message_unpack (&proto__lap__descriptor,
                                allocator, len, data);
}
void   proto__lap__free_unpacked
                     (ProtoLap *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__lap__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__lap__data__init
                     (ProtoLapData         *message)
{
  static const ProtoLapData init_value = PROTO__LAP__DATA__INIT;
  *message = init_value;
}
size_t proto__lap__data__get_packed_size
                     (const ProtoLapData *message)
{
  assert(message->base.descriptor == &proto__lap__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__lap__data__pack
                     (const ProtoLapData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__lap__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__lap__data__pack_to_buffer
                     (const ProtoLapData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__lap__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoLapData *
       proto__lap__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoLapData *)
     protobuf_c_message_unpack (&proto__lap__data__descriptor,
                                allocator, len, data);
}
void   proto__lap__data__free_unpacked
                     (ProtoLapData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__lap__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__mcu__data__init
                     (ProtoMcuData         *message)
{
  static const ProtoMcuData init_value = PROTO__MCU__DATA__INIT;
  *message = init_value;
}
size_t proto__mcu__data__get_packed_size
                     (const ProtoMcuData *message)
{
  assert(message->base.descriptor == &proto__mcu__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__mcu__data__pack
                     (const ProtoMcuData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__mcu__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__mcu__data__pack_to_buffer
                     (const ProtoMcuData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__mcu__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoMcuData *
       proto__mcu__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoMcuData *)
     protobuf_c_message_unpack (&proto__mcu__data__descriptor,
                                allocator, len, data);
}
void   proto__mcu__data__free_unpacked
                     (ProtoMcuData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__mcu__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__payloaded__message__init
                     (ProtoPayloadedMessage         *message)
{
  static const ProtoPayloadedMessage init_value = PROTO__PAYLOADED__MESSAGE__INIT;
  *message = init_value;
}
size_t proto__payloaded__message__get_packed_size
                     (const ProtoPayloadedMessage *message)
{
  assert(message->base.descriptor == &proto__payloaded__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__payloaded__message__pack
                     (const ProtoPayloadedMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__payloaded__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__payloaded__message__pack_to_buffer
                     (const ProtoPayloadedMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__payloaded__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoPayloadedMessage *
       proto__payloaded__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoPayloadedMessage *)
     protobuf_c_message_unpack (&proto__payloaded__message__descriptor,
                                allocator, len, data);
}
void   proto__payloaded__message__free_unpacked
                     (ProtoPayloadedMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__payloaded__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__event__field_descriptors[6] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ProtoEvent, has_id),
    offsetof(ProtoEvent, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ProtoEvent, has_type),
    offsetof(ProtoEvent, type),
    &proto__event__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "severity",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ProtoEvent, has_severity),
    offsetof(ProtoEvent, severity),
    &proto__severity__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "created_at",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ProtoEvent, has_created_at),
    offsetof(ProtoEvent, created_at),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "displayed_since",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ProtoEvent, has_displayed_since),
    offsetof(ProtoEvent, displayed_since),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "text",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtoEvent, text),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__event__field_indices_by_name[] = {
  3,   /* field[3] = created_at */
  4,   /* field[4] = displayed_since */
  0,   /* field[0] = id */
  2,   /* field[2] = severity */
  5,   /* field[5] = text */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange proto__event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor proto__event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Proto_Event",
  "ProtoEvent",
  "ProtoEvent",
  "",
  sizeof(ProtoEvent),
  6,
  proto__event__field_descriptors,
  proto__event__field_indices_by_name,
  1,  proto__event__number_ranges,
  (ProtobufCMessageInit) proto__event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__command__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ProtoCommand, has_type),
    offsetof(ProtoCommand, type),
    &proto__command__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ProtoCommand, has_id),
    offsetof(ProtoCommand, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "created",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ProtoCommand, has_created),
    offsetof(ProtoCommand, created),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "handled",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ProtoCommand, has_handled),
    offsetof(ProtoCommand, handled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__command__field_indices_by_name[] = {
  2,   /* field[2] = created */
  3,   /* field[3] = handled */
  1,   /* field[1] = id */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange proto__command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor proto__command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Proto_Command",
  "ProtoCommand",
  "ProtoCommand",
  "",
  sizeof(ProtoCommand),
  4,
  proto__command__field_descriptors,
  proto__command__field_indices_by_name,
  1,  proto__command__number_ranges,
  (ProtobufCMessageInit) proto__command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__car__sensor__field_descriptors[2] =
{
  {
    "temp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ProtoCarSensor, has_temp),
    offsetof(ProtoCarSensor, temp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "preassure",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(ProtoCarSensor, has_preassure),
    offsetof(ProtoCarSensor, preassure),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__car__sensor__field_indices_by_name[] = {
  1,   /* field[1] = preassure */
  0,   /* field[0] = temp */
};
static const ProtobufCIntRange proto__car__sensor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__car__sensor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Proto_Car_Sensor",
  "ProtoCarSensor",
  "ProtoCarSensor",
  "",
  sizeof(ProtoCarSensor),
  2,
  proto__car__sensor__field_descriptors,
  proto__car__sensor__field_indices_by_name,
  1,  proto__car__sensor__number_ranges,
  (ProtobufCMessageInit) proto__car__sensor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__stint__data__field_descriptors[4] =
{
  {
    "running",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ProtoStintData, has_running),
    offsetof(ProtoStintData, running),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enabled",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ProtoStintData, has_enabled),
    offsetof(ProtoStintData, enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ProtoStintData, has_target),
    offsetof(ProtoStintData, target),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "elapsed",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ProtoStintData, has_elapsed),
    offsetof(ProtoStintData, elapsed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__stint__data__field_indices_by_name[] = {
  3,   /* field[3] = elapsed */
  1,   /* field[1] = enabled */
  0,   /* field[0] = running */
  2,   /* field[2] = target */
};
static const ProtobufCIntRange proto__stint__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor proto__stint__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Proto_Stint_Data",
  "ProtoStintData",
  "ProtoStintData",
  "",
  sizeof(ProtoStintData),
  4,
  proto__stint__data__field_descriptors,
  proto__stint__data__field_indices_by_name,
  1,  proto__stint__data__number_ranges,
  (ProtobufCMessageInit) proto__stint__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__lap__field_descriptors[2] =
{
  {
    "lap_no",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ProtoLap, has_lap_no),
    offsetof(ProtoLap, lap_no),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lap_time_ms",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ProtoLap, has_lap_time_ms),
    offsetof(ProtoLap, lap_time_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__lap__field_indices_by_name[] = {
  0,   /* field[0] = lap_no */
  1,   /* field[1] = lap_time_ms */
};
static const ProtobufCIntRange proto__lap__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__lap__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Proto_Lap",
  "ProtoLap",
  "ProtoLap",
  "",
  sizeof(ProtoLap),
  2,
  proto__lap__field_descriptors,
  proto__lap__field_indices_by_name,
  1,  proto__lap__number_ranges,
  (ProtobufCMessageInit) proto__lap__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__lap__data__field_descriptors[4] =
{
  {
    "lap_no",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ProtoLapData, has_lap_no),
    offsetof(ProtoLapData, lap_no),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "best_lap",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ProtoLapData, has_best_lap),
    offsetof(ProtoLapData, best_lap),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_lap",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ProtoLapData, has_current_lap),
    offsetof(ProtoLapData, current_lap),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "laps",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ProtoLapData, n_laps),
    offsetof(ProtoLapData, laps),
    &proto__lap__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__lap__data__field_indices_by_name[] = {
  1,   /* field[1] = best_lap */
  2,   /* field[2] = current_lap */
  0,   /* field[0] = lap_no */
  3,   /* field[3] = laps */
};
static const ProtobufCIntRange proto__lap__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor proto__lap__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Proto_Lap_Data",
  "ProtoLapData",
  "ProtoLapData",
  "",
  sizeof(ProtoLapData),
  4,
  proto__lap__data__field_descriptors,
  proto__lap__data__field_indices_by_name,
  1,  proto__lap__data__number_ranges,
  (ProtobufCMessageInit) proto__lap__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__mcu__data__field_descriptors[9] =
{
  {
    "network_time_adjustment",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ProtoMcuData, has_network_time_adjustment),
    offsetof(ProtoMcuData, network_time_adjustment),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "water",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtoMcuData, water),
    &proto__car__sensor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "oil",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtoMcuData, oil),
    &proto__car__sensor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gas",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtoMcuData, gas),
    &proto__car__sensor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stint",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtoMcuData, stint),
    &proto__stint__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lap_data",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtoMcuData, lap_data),
    &proto__lap__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "events",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ProtoMcuData, n_events),
    offsetof(ProtoMcuData, events),
    &proto__event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outgoing_commands",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ProtoMcuData, n_outgoing_commands),
    offsetof(ProtoMcuData, outgoing_commands),
    &proto__command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "incoming_commands",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ProtoMcuData, n_incoming_commands),
    offsetof(ProtoMcuData, incoming_commands),
    &proto__command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__mcu__data__field_indices_by_name[] = {
  6,   /* field[6] = events */
  3,   /* field[3] = gas */
  8,   /* field[8] = incoming_commands */
  5,   /* field[5] = lap_data */
  0,   /* field[0] = network_time_adjustment */
  2,   /* field[2] = oil */
  7,   /* field[7] = outgoing_commands */
  4,   /* field[4] = stint */
  1,   /* field[1] = water */
};
static const ProtobufCIntRange proto__mcu__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor proto__mcu__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Proto_Mcu_Data",
  "ProtoMcuData",
  "ProtoMcuData",
  "",
  sizeof(ProtoMcuData),
  9,
  proto__mcu__data__field_descriptors,
  proto__mcu__data__field_indices_by_name,
  1,  proto__mcu__data__number_ranges,
  (ProtobufCMessageInit) proto__mcu__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__payloaded__message__field_descriptors[8] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ProtoPayloadedMessage, has_type),
    offsetof(ProtoPayloadedMessage, type),
    &proto__lora__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq_nr",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ProtoPayloadedMessage, has_seq_nr),
    offsetof(ProtoPayloadedMessage, seq_nr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "water_sensor",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtoPayloadedMessage, water_sensor),
    &proto__car__sensor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "oil_sensor",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtoPayloadedMessage, oil_sensor),
    &proto__car__sensor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gas_sensor",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtoPayloadedMessage, gas_sensor),
    &proto__car__sensor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lap_data",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtoPayloadedMessage, lap_data),
    &proto__lap__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stint_data",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtoPayloadedMessage, stint_data),
    &proto__stint__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "acks",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ProtoPayloadedMessage, n_acks),
    offsetof(ProtoPayloadedMessage, acks),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__payloaded__message__field_indices_by_name[] = {
  7,   /* field[7] = acks */
  4,   /* field[4] = gas_sensor */
  5,   /* field[5] = lap_data */
  3,   /* field[3] = oil_sensor */
  1,   /* field[1] = seq_nr */
  6,   /* field[6] = stint_data */
  0,   /* field[0] = type */
  2,   /* field[2] = water_sensor */
};
static const ProtobufCIntRange proto__payloaded__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor proto__payloaded__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Proto_Payloaded_Message",
  "ProtoPayloadedMessage",
  "ProtoPayloadedMessage",
  "",
  sizeof(ProtoPayloadedMessage),
  8,
  proto__payloaded__message__field_descriptors,
  proto__payloaded__message__field_indices_by_name,
  1,  proto__payloaded__message__number_ranges,
  (ProtobufCMessageInit) proto__payloaded__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue proto__severity__enum_values_by_number[4] =
{
  { "POSITIVE", "PROTO__SEVERITY__POSITIVE", 1 },
  { "NORMAL", "PROTO__SEVERITY__NORMAL", 2 },
  { "WARN", "PROTO__SEVERITY__WARN", 3 },
  { "CRIT", "PROTO__SEVERITY__CRIT", 4 },
};
static const ProtobufCIntRange proto__severity__value_ranges[] = {
{1, 0},{0, 4}
};
static const ProtobufCEnumValueIndex proto__severity__enum_values_by_name[4] =
{
  { "CRIT", 3 },
  { "NORMAL", 1 },
  { "POSITIVE", 0 },
  { "WARN", 2 },
};
const ProtobufCEnumDescriptor proto__severity__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Proto_Severity",
  "Proto_Severity",
  "ProtoSeverity",
  "",
  4,
  proto__severity__enum_values_by_number,
  4,
  proto__severity__enum_values_by_name,
  1,
  proto__severity__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue proto__event__type__enum_values_by_number[4] =
{
  { "EVT_NONE", "PROTO__EVENT__TYPE__EVT_NONE", 1 },
  { "EVT_LAP", "PROTO__EVENT__TYPE__EVT_LAP", 2 },
  { "EVT_TIME_REMAIN", "PROTO__EVENT__TYPE__EVT_TIME_REMAIN", 3 },
  { "EVT_STATE_CHANGE", "PROTO__EVENT__TYPE__EVT_STATE_CHANGE", 4 },
};
static const ProtobufCIntRange proto__event__type__value_ranges[] = {
{1, 0},{0, 4}
};
static const ProtobufCEnumValueIndex proto__event__type__enum_values_by_name[4] =
{
  { "EVT_LAP", 1 },
  { "EVT_NONE", 0 },
  { "EVT_STATE_CHANGE", 3 },
  { "EVT_TIME_REMAIN", 2 },
};
const ProtobufCEnumDescriptor proto__event__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Proto_Event_Type",
  "Proto_Event_Type",
  "ProtoEventType",
  "",
  4,
  proto__event__type__enum_values_by_number,
  4,
  proto__event__type__enum_values_by_name,
  1,
  proto__event__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue proto__command__type__enum_values_by_number[4] =
{
  { "COM_NONE", "PROTO__COMMAND__TYPE__COM_NONE", 1 },
  { "COM_PIT", "PROTO__COMMAND__TYPE__COM_PIT", 2 },
  { "COM_STINT_OVER", "PROTO__COMMAND__TYPE__COM_STINT_OVER", 3 },
  { "COM_FCK", "PROTO__COMMAND__TYPE__COM_FCK", 4 },
};
static const ProtobufCIntRange proto__command__type__value_ranges[] = {
{1, 0},{0, 4}
};
static const ProtobufCEnumValueIndex proto__command__type__enum_values_by_name[4] =
{
  { "COM_FCK", 3 },
  { "COM_NONE", 0 },
  { "COM_PIT", 1 },
  { "COM_STINT_OVER", 2 },
};
const ProtobufCEnumDescriptor proto__command__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Proto_Command_Type",
  "Proto_Command_Type",
  "ProtoCommandType",
  "",
  4,
  proto__command__type__enum_values_by_number,
  4,
  proto__command__type__enum_values_by_name,
  1,
  proto__command__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue proto__lora__type__enum_values_by_number[7] =
{
  { "LORA_ACK", "PROTO__LORA__TYPE__LORA_ACK", 1 },
  { "LORA_OIL", "PROTO__LORA__TYPE__LORA_OIL", 2 },
  { "LORA_WATER", "PROTO__LORA__TYPE__LORA_WATER", 3 },
  { "LORA_GAS", "PROTO__LORA__TYPE__LORA_GAS", 4 },
  { "LORA_LAP", "PROTO__LORA__TYPE__LORA_LAP", 5 },
  { "LORA_STINT", "PROTO__LORA__TYPE__LORA_STINT", 6 },
  { "LORA_COMMAND", "PROTO__LORA__TYPE__LORA_COMMAND", 7 },
};
static const ProtobufCIntRange proto__lora__type__value_ranges[] = {
{1, 0},{0, 7}
};
static const ProtobufCEnumValueIndex proto__lora__type__enum_values_by_name[7] =
{
  { "LORA_ACK", 0 },
  { "LORA_COMMAND", 6 },
  { "LORA_GAS", 3 },
  { "LORA_LAP", 4 },
  { "LORA_OIL", 1 },
  { "LORA_STINT", 5 },
  { "LORA_WATER", 2 },
};
const ProtobufCEnumDescriptor proto__lora__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Proto_Lora_Type",
  "Proto_Lora_Type",
  "ProtoLoraType",
  "",
  7,
  proto__lora__type__enum_values_by_number,
  7,
  proto__lora__type__enum_values_by_name,
  1,
  proto__lora__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
